name: Chat_Desktop
description: A new Flutter project.

publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.2.0
  cloud_firestore: ^5.0.1
  firebase_auth: ^5.1.2

  # State
  flutter_riverpod: ^2.5.1

  # Data Classes / Models
  freezed_annotation: ^2.4.1

  # UI
  google_fonts: ^6.2.1
  flex_color_scheme: ^7.3.1

  # Utils
  uuid: ^4.2.2
  intl: ^0.19.0
  desktop_drop: ^0.5.0
  rxdart: ^0.28.0
  file_picker: ^8.0.0
  json_annotation: ^4.9.0

flutter:
  assets:
    - assets/icons/

dev_dependencies:
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  freezed: ^2.4.5
  json_serializable: ^6.7.1
